### PR TITLE
fixed count error

### LINKED ISSUE #70: Wrong question count
https://github.com/certificationy/certificationy-cli/issues/25

Start command in certificationy-cli gives question count more than actual questions exist.

```
$ php certificationy.php start --number 1000
Starting a new set of 252 questions (available questions: 425)
$ grep "\-$" vendor/certificationy/*/data/* | wc -l
252
```

### PR DESCRIPTION
**Pull request by mazhuravlev**
resolve #70 
[Loader::$count](https://github.com/certificationy/certificationy/blob/master/Certification/Loader.php#L27) should be private, but it can break public API.

If right side [of this](https://github.com/certificationy/certificationy/blob/master/Certification/Loader.php#L79) will be executed, when Loader::count() gets called before questions or categories load, missing argument warning will be thrown, so I changed that part in favor of throwing exception.

### CODE REVIEW

File: Certification/Loader.php [hunk 1]
```diff
@@ -86,13 +106,13 @@ static public function count()
      *
      * @return array
      */
-    static protected function prepareFromYaml(array $categories = array(), $path)
+    protected static function prepareFromYaml(array $categories = array(), $path)
```
Comment (mickaelandrieu) [inline Certification/Loader.php]: I'm so busy theses times, sorry ... but my curiosity forces me to ask you: why reverse ``static`` and ``public`` ? :D

**Comment by mazhuravlev** [comment]
It's in [PSR-2](http://www.php-fig.org/psr/psr-2/).

> Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.

**Comment by mickaelandrieu** [comment]
Ok for me :)

Thank you @mazhuravlev
